version: "3.8"

services:
  app:
    container_name: orderdrinks-elysia
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - FONTEND_URL=${FONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
      - BRANCH_ID=${BRANCH_ID}
      - API_KEY=${API_KEY}
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - LINE_LOGIN_CHANNEL_ID=${LINE_LOGIN_CHANNEL_ID}
      - LINE_LOGIN_CHANNEL_SECRET=${LINE_LOGIN_CHANNEL_SECRET}
      - LINE_LOGIN_CALLBACK_URL=${LINE_LOGIN_CALLBACK_URL}
    depends_on:
      - mongodb
    volumes:
      - ./image:/app/image
    networks:
      - My-Orderdrinks

  mongodb:
    image: mongo:latest
    ports:
      - "35940:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - My-Orderdrinks

networks:
  My-Orderdrinks:
    driver: bridge

volumes:
  mongodb_data:
