version: "3.8"

services:
  app:
    container_name: orderdrinks-elysia
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/orderdrinks
      - FONTEND_URL=http://orderdrinks.webhop.me:3000
      - JWT_SECRET=secret
      - JWT_EXPIRE=7d
      - BRANCH_ID=your_branch_id
      - API_KEY=your_api_key
      - LINE_CHANNEL_ACCESS_TOKEN=your_line_channel_access_token
      - LINE_CHANNEL_SECRET=your_line_channel_secret
      - LINE_LOGIN_CHANNEL_ID=your_line_login_channel_id
      - LINE_LOGIN_CHANNEL_SECRET=your_line_login_channel_secret
      - LINE_LOGIN_CALLBACK_URL=your_line_login_callback_url
    depends_on:
      - mongodb
    networks:
      - My-Orderdrinks

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - My-Orderdrinks

networks:
  My-Orderdrinks:
    driver: bridge

volumes:
  mongodb_data:
